apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::883656809667:role/eksctl-final-pipeline-nodegroup-n-NodeInstanceRole-SN2VOE7SRN77
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::883656809667:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-28T19:27:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1279"
  uid: c817660c-32da-44bf-9b13-80d5a237f799
